FROM node:20.8.1
 
#WORKDIR /app
 
COPY ./vue/src/server/package.json package.json
#COPY ./vue/package-lock.json package-lock.json
COPY ./vue/src/server/ . 
 
RUN npm install

EXPOSE 3306 8080

CMD [ "node", "server.js" ]
