FROM debian:bookworm AS builder

WORKDIR /tmp
RUN apt-get update && apt-get upgrade -y && \
apt-get install -y curl sudo ca-certificates gnupg
RUN mkdir -p /etc/apt/keyrings && \
rm -f /etc/apt/keyrings/nodesource.gpg
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
#RUN NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && \
apt-get install -y nodejs git

COPY ./vue ./vue
RUN cd vue && npm i && npm run build

#Debugging Path Directory
RUN echo $(ls ./vue/dist/)

FROM nginx:1.18.0
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY letsmakantogether.com /etc/nginx/sites-available/letsmakantogether.com
COPY hosts /etc/hosts
COPY --from=builder /tmp/vue/dist/ /var/www/html/letsmakantogether/
#COPY --from=builder /tmp/dist/* /var/www/html/angular
COPY openssl.cnf ./
RUN apt update && apt install -y openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -config openssl.cnf
RUN openssl dhparam -out /etc/nginx/dhparam.pem 2048
COPY self-signed.conf /etc/nginx/snippets/self-signed.conf
COPY ssl-params.conf /etc/nginx/snippets/ssl-params.conf
COPY letsmakantogether.com /etc/nginx/sites-available/letsmakantogether.com
RUN apt update && apt upgrade -y && apt install -y vim

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]

